# Exploratory Data Analysis <a class="anchor" id="first-bullet"></a>

### Tabla de Contenido:
* [CLIENTES AUTOSERVICIOS](#CLIENTES-AUTOSERVICIOS)
* [DESCRIPTIVO CLIENTES](#DESCRIPTIVO-CLIENTES)
* [REVISION DE CAMPOS](#REVISION-DE-CAMPOS)
* [DESCRIPCION DE CLIENTES](#DESCRIPCION-DE-CLIENTES)
    * [DESCRIPTIVO CLIENTES](#DESCRIPTIVO-CLIENTES)
    * [DESCRIPTIVO SUCURSALES](#DESCRIPTIVO-SUCURSALES)

* [Segmentacion Geografica Lima Provincia](#Segmentacion-Geografica-Lima-Provincia)

---

In [1]:
from IPython.display import Markdown as md
import numpy as np
import pandas as pd
from cycler import cycler
import matplotlib
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import math


from itertools import cycle, islice
pd.set_option('display.float_format', lambda x: '%.3f' % x)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

#Libreria yellowbrick
# from yellowbrick.target import BalancedBinningReference

%load_ext autoreload
%autoreload 2
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

# from mlxtend.frequent_patterns import apriori
# from mlxtend.frequent_patterns import association_rules

import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
# import eda_functions as eda
from tqdm import tqdm

-----------------------

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import plot_roc_curve
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
pd.options.display.float_format = '{:.2f}'.format

Data set gotten from:
- $ wget http://www.cryptodatadownload.com/cdd/Gemini_ETHUSD_d.csv

In [37]:
df = pd.read_csv('./Gemini_ETHUSD_d.csv', skiprows=1)

df.Date = pd.to_datetime(df.Date, format='%Y-%m-%d')
df = df.sort_values('Date').reset_index()

In [38]:
df.head()

   index       Date  Symbol  Open  High   Low  Close  Volume ETH  Volume USD
0   1528 2016-05-09  ETHUSD 12.00 12.00  9.36   9.98     1317.90    12885.06
1   1527 2016-05-10  ETHUSD  9.98  9.98  9.36   9.68      672.06     6578.20
2   1526 2016-05-11  ETHUSD  9.68 10.47  9.68  10.43     3052.51    30978.11
3   1525 2016-05-12  ETHUSD 10.43 12.00  9.92  10.20     2072.56    22183.39
4   1524 2016-05-13  ETHUSD 10.20 11.59 10.20  10.69     1769.71    18923.55

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1529 entries, 0 to 1528
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       1529 non-null   int64
 1   Date        1529 non-null   datetime64[ns]
 2   Symbol      1529 non-null   object
 3   Open        1529 non-null   float64
 4   High        1529 non-null   float64
 5   Low         1529 non-null   float64
 6   Close       1529 non-null   float64
 7   Volume ETH  1529 non-null   float64
 8   Volume USD  1529 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(1)
memory usage: 107.6+ KB

In [40]:
STEPS = 64
df['d0'] = df.Close

for i in range(1,STEPS):
    col_name = 'd{}'.format(i)
    df[col_name] = df['d0'].shift(periods=-1 * i)
df = df.dropna()

In [41]:
df = df.iloc[:,9:]

In [42]:
df.head()

,d0,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31,d32,d33,d34,d35,d36,d37,d38,d39,d40,d41,d42,d43,d44,d45,d46,d47,d48,d49,d50,d51,d52,d53,d54,d55,d56,d57,d58,d59,d60,d61,d62,d63
0,9.98,9.68,10.43,10.20,10.69,10.25,10.06,11.37,12.23,13.30,14.50,13.90,13.97,14.20,13.55,12.82,12.53,12.60,11.39,11.81,12.53,12.66,14.18,13.95,13.90,14.02,13.86,13.91,14.16,14.50,14.51,14.47,13.97,14.11,15.75,17.64,18.92,18.39,20.95,15.65,11.42,12.59,11.85,12.80,13.43,13.76,14.14,14.49,13.82,15.29,12.26,12.95,12.50,12.26,12.09,11.89,11.45,10.69,11.00,10.10,11.57,11.09,11.13,10.83
1,9.68,10.43,10.20,10.69,10.25,10.06,11.37,12.23,13.30,14.50,13.90,13.97,14.20,13.55,12.82,12.53,12.60,11.39,11.81,12.53,12.66,14.18,13.95,13.90,14.02,13.86,13.91,14.16,14.50,14.51,14.47,13.97,14.11,15.75,17.64,18.92,18.39,20.95,15.65,11.42,12.59,11.85,12.80,13.43,13.76,14.14,14.49,13.82,15.29,12.26,12.95,12.50,12.26,12.09,11.89,11.45,10.69,11.00,10.10,11.57,11.09,11.13,10.83,10.87
2,10.43,10.20,10.69,10.25,10.06,11.37,12.23,13.30,14.50,13.90,13.97,14.20,13.55,12.82,12.53,12.60,11.39,11.81,12.53,12.66,14.18,13.95,13.90,14.02,13.86,13.91,14.16,14.50,14.51,14.47,13.97,14.11,15.75,17.64,18.92,18.39,20.95,15.65,11.42,12.59,11.85,12.80,13.43,13.76,14.14,14.49,13.82,15.29,12.26,12.95,12.50,12.26,12.09,11.89,11.45,10.69,11.00,10.10,11.57,11.09,11.13,10.83,10.87,10.76
3,10.20,10.69,10.25,10.06,11.37,12.23,13.30,14.50,13.90,13.97,14.20,13.55,12.82,12.53,12.60,11.39,11.81,12.53,12.66,14.18,13.95,13.90,14.02,13.86,13.91,14.16,14.50,14.51,14.47,13.97,14.11,15.75,17.64,18.92,18.39,20.95,15.65,11.42,12.59,11.85,12.80,13.43,13.76,14.14,14.49,13.82,15.29,12.26,12.95,12.50,12.26,12.09,11.89,11.45,10.69,11.00,10.10,11.57,11.09,11.13,10.83,10.87,10.76,11.52
4,10.69,10.25,10.06,11.37,12.23,13.30,14.50,13.90,13.97,14.20,13.55,12.82,12.53,12.60,11.39,11.81,12.53,12.66,14.18,13.95,13.90,14.02,13.86,13.91,14.16,14.50,14.51,14.47,13.97,14.11,15.75,17.64,18.92,18.39,20.95,15.65,11.42,12.59,11.85,12.80,13.43,13.76,14.14,14.49,13.82,15.29,12.26,12.95,12.50,12.26,12.09,11.89,11.45,10.69,11.00,10.10,11.57,11.09,11.13,10.83,10.87,10.76,11.52,12.20

In [ ]:
X = df.iloc[:, :TRAIN_STEPS]
y = df.iloc[:, TRAIN_STEPS:]

X_train = X.iloc[:SPLIT_IDX, :]
y_train = y.iloc[:SPLIT_IDX, :]

X_test = X.iloc[SPLIT_IDX:, :]
y_test = y.iloc[SPLIT_IDX:, :]

In [ ]:
def build_model(_alpha, _l1_ratio):
    estimator = ElasticNet(
        alpha=_alpha,
        l1_ratio=_l1_ratio,
        fit_intercept=True,
        normalize=False,
        precompute=False,
        max_iter=16,
        copy_X=True,
        tol=0.1,
        warm_start=False,
        positive=False,
        random_state=None,
        selection='random'
    )

    return MultiOutputRegressor(estimator, n_jobs=4)

In [ ]:
model = build_model(_alpha=1.0, _l1_ratio=0.3)
kfcv = KFold(n_splits=5)
scores = cross_val_score(model, X_train, y_train, cv=kfcv, scoring=r2)
print("Loss: {0:.3f} (+/- {1:.3f})".format(scores.mean(), scores.std()))

In [ ]:
model = build_model(_alpha=1.0, _l1_ratio=0.3)
tscv = TimeSeriesSplit(n_splits=5)
scores = cross_val_score(model, X_train, y_train, cv=tscv, scoring=r2)
print("Loss: {0:.3f} (+/- {1:.3f})".format(scores.mean(), scores.std()))

In [ ]:
class BlockingTimeSeriesSplit():
    def __init__(self, n_splits):
        self.n_splits = n_splits
    
    def get_n_splits(self, X, y, groups):
        return self.n_splits
    
    def split(self, X, y=None, groups=None):
        n_samples = len(X)
        k_fold_size = n_samples // self.n_splits
        indices = np.arange(n_samples)

        margin = 0
        for i in range(self.n_splits):
            start = i * k_fold_size
            stop = start + k_fold_size
            mid = int(0.8 * (stop - start)) + start
            yield indices[start: mid], indices[mid + margin: stop]

In [ ]:
model = build_model(_alpha=1.0, _l1_ratio=0.3)
btscv = BlockingTimeSeriesSplit(n_splits=5)
scores = cross_val_score(model, X_train, y_train, cv=btscv, scoring=r2)
print("Loss: {0:.3f} (+/- {1:.3f})".format(scores.mean(), scores.std()))

In [ ]:
params = {
    'estimator__alpha':(0.1, 0.3, 0.5, 0.7, 0.9),
    'estimator__l1_ratio':(0.1, 0.3, 0.5, 0.7, 0.9)
}

for i in range(100):
    model = build_model(_alpha=1.0, _l1_ratio=0.3)

    finder = GridSearchCV(
        estimator=model,
        param_grid=params,
        scoring=r2,
        fit_params=None,
        n_jobs=None,
        iid=False,
        refit=False,
        cv=kfcv,  # change this to the splitter subject to test
        verbose=1,
        pre_dispatch=8,
        error_score=-999,
        return_train_score=True
    )

    finder.fit(X_train, y_train)

    best_params = finder.best_params_